name: Animal Search Deploy
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
    run-Demo-script:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Copy code to EC2
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "./"
            target: "~/deploy"

        - name: Deploy Code on EC2
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.REMOTE_HOST }}
           username: ${{ secrets.REMOTE_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd ~/deploy/animal-search/
             docker-compose up -d
             docker ps
