name: Run Bash Jobs
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
    run-bash-script:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout My code
          uses: actions/checkout@v4
        - name: list repo files
          run: |
            ls
            echo "My name is peter"
    run-Demo-script:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout My code
          uses: actions/checkout@v4
        - name: Make directory
          run: |
            mkdir -p acada_github/workflow
            touch acada_github/workflow/acada{1..10}
            ls -al acada_github/workflow
        - name: check runner hostname
          run: | 
             hostname -f
             hostname -I

        - name: deploy to aws
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "./"
            target: "~/deploy"
        - name: ssh 
          uses: appleboy/ssh-action@master
          with:
           host: ${{ secrets.REMOTE_HOST }}
           username: ${{ secrets.REMOTE_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             ls ~/deploy
             cd ~/deploy/gh_actions/animal-search/
             docker-compose up -d 
             docker ps
