name: Run Python Script
on:
  #workflow_dispatch:
  push:
     branches:
       - main
  pull_request:
    branches:
       - main

jobs:
   run-python-script:
     runs-on: self-hosted
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run python Script
        run: python hello.py
